
/*
* opcodes.c was last generated from the data at http://obelisk.me.uk/6502/reference.html on 2020-08-17 22:59:39 
*/


struct opcode {
    char opName[4];
    char opShortDesc[70];
    char addressingMode[15];
    int additionalBytes;
};

struct opcode opcodes[256] = {
{"BRK ", " Force Interrupt", "Implied", 0},
{"ORA ", " Logical Inclusive OR", "Indirect_X", 1},
{"SCF", " Stop, Catch Fire: Illegal Opcode", "None", 0},
{"SCF", " Stop, Catch Fire: Illegal Opcode", "None", 0},
{"SCF", " Stop, Catch Fire: Illegal Opcode", "None", 0},
{"ORA ", " Logical Inclusive OR", "ZeroPage", 1},
{"ASL ", " Arithmetic Shift Left", "ZeroPage", 1},
{"SCF", " Stop, Catch Fire: Illegal Opcode", "None", 0},
{"PHP ", " Push Processor Status", "Implied", 0},
{"ORA ", " Logical Inclusive OR", "Immediate", 1},
{"ASL ", " Arithmetic Shift Left", "Accumulator", 0},
{"SCF", " Stop, Catch Fire: Illegal Opcode", "None", 0},
{"SCF", " Stop, Catch Fire: Illegal Opcode", "None", 0},
{"ORA ", " Logical Inclusive OR", "Absolute", 2},
{"ASL ", " Arithmetic Shift Left", "Absolute", 2},
{"SCF", " Stop, Catch Fire: Illegal Opcode", "None", 0},
{"BPL ", " Branch if Positive", "Relative", 1},
{"ORA ", " Logical Inclusive OR", "Indirect_Y", 1},
{"SCF", " Stop, Catch Fire: Illegal Opcode", "None", 0},
{"SCF", " Stop, Catch Fire: Illegal Opcode", "None", 0},
{"SCF", " Stop, Catch Fire: Illegal Opcode", "None", 0},
{"ORA ", " Logical Inclusive OR", "ZeroPage_X", 1},
{"ASL ", " Arithmetic Shift Left", "ZeroPage_X", 1},
{"SCF", " Stop, Catch Fire: Illegal Opcode", "None", 0},
{"CLC ", " Clear Carry Flag", "Implied", 0},
{"ORA ", " Logical Inclusive OR", "Absolute_Y", 2},
{"SCF", " Stop, Catch Fire: Illegal Opcode", "None", 0},
{"SCF", " Stop, Catch Fire: Illegal Opcode", "None", 0},
{"SCF", " Stop, Catch Fire: Illegal Opcode", "None", 0},
{"ORA ", " Logical Inclusive OR", "Absolute_X", 2},
{"ASL ", " Arithmetic Shift Left", "Absolute_X", 2},
{"SCF", " Stop, Catch Fire: Illegal Opcode", "None", 0},
{"JSR ", " Jump to Subroutine", "Absolute", 2},
{"AND ", " Logical AND", "Indirect_X", 1},
{"SCF", " Stop, Catch Fire: Illegal Opcode", "None", 0},
{"SCF", " Stop, Catch Fire: Illegal Opcode", "None", 0},
{"BIT ", " Bit Test", "ZeroPage", 1},
{"AND ", " Logical AND", "ZeroPage", 1},
{"ROL ", " Rotate Left", "ZeroPage", 1},
{"SCF", " Stop, Catch Fire: Illegal Opcode", "None", 0},
{"PLP ", " Pull Processor Status", "Implied", 0},
{"AND ", " Logical AND", "Immediate", 1},
{"ROL ", " Rotate Left", "Accumulator", 0},
{"SCF", " Stop, Catch Fire: Illegal Opcode", "None", 0},
{"BIT ", " Bit Test", "Absolute", 2},
{"AND ", " Logical AND", "Absolute", 2},
{"ROL ", " Rotate Left", "Absolute", 2},
{"SCF", " Stop, Catch Fire: Illegal Opcode", "None", 0},
{"BMI ", " Branch if Minus", "Relative", 1},
{"AND ", " Logical AND", "Indirect_Y", 1},
{"SCF", " Stop, Catch Fire: Illegal Opcode", "None", 0},
{"SCF", " Stop, Catch Fire: Illegal Opcode", "None", 0},
{"SCF", " Stop, Catch Fire: Illegal Opcode", "None", 0},
{"AND ", " Logical AND", "ZeroPage_X", 1},
{"ROL ", " Rotate Left", "ZeroPage_X", 1},
{"SCF", " Stop, Catch Fire: Illegal Opcode", "None", 0},
{"SEC ", " Set Carry Flag", "Implied", 0},
{"AND ", " Logical AND", "Absolute_Y", 2},
{"SCF", " Stop, Catch Fire: Illegal Opcode", "None", 0},
{"SCF", " Stop, Catch Fire: Illegal Opcode", "None", 0},
{"SCF", " Stop, Catch Fire: Illegal Opcode", "None", 0},
{"AND ", " Logical AND", "Absolute_X", 2},
{"ROL ", " Rotate Left", "Absolute_X", 2},
{"SCF", " Stop, Catch Fire: Illegal Opcode", "None", 0},
{"RTI ", " Return from Interrupt", "Implied", 0},
{"EOR ", " Exclusive OR", "Indirect_X", 1},
{"SCF", " Stop, Catch Fire: Illegal Opcode", "None", 0},
{"SCF", " Stop, Catch Fire: Illegal Opcode", "None", 0},
{"SCF", " Stop, Catch Fire: Illegal Opcode", "None", 0},
{"EOR ", " Exclusive OR", "ZeroPage", 1},
{"LSR ", " Logical Shift Right", "ZeroPage", 1},
{"SCF", " Stop, Catch Fire: Illegal Opcode", "None", 0},
{"PHA ", " Push Accumulator", "Implied", 0},
{"EOR ", " Exclusive OR", "Immediate", 1},
{"LSR ", " Logical Shift Right", "Accumulator", 0},
{"SCF", " Stop, Catch Fire: Illegal Opcode", "None", 0},
{"JMP ", " Jump", "Absolute", 2},
{"EOR ", " Exclusive OR", "Absolute", 2},
{"LSR ", " Logical Shift Right", "Absolute", 2},
{"SCF", " Stop, Catch Fire: Illegal Opcode", "None", 0},
{"BVC ", " Branch if Overflow Clear", "Relative", 1},
{"EOR ", " Exclusive OR", "Indirect_Y", 1},
{"SCF", " Stop, Catch Fire: Illegal Opcode", "None", 0},
{"SCF", " Stop, Catch Fire: Illegal Opcode", "None", 0},
{"SCF", " Stop, Catch Fire: Illegal Opcode", "None", 0},
{"EOR ", " Exclusive OR", "ZeroPage_X", 1},
{"LSR ", " Logical Shift Right", "ZeroPage_X", 1},
{"SCF", " Stop, Catch Fire: Illegal Opcode", "None", 0},
{"CLI ", " Clear Interrupt Disable", "Implied", 0},
{"EOR ", " Exclusive OR", "Absolute_Y", 2},
{"SCF", " Stop, Catch Fire: Illegal Opcode", "None", 0},
{"SCF", " Stop, Catch Fire: Illegal Opcode", "None", 0},
{"SCF", " Stop, Catch Fire: Illegal Opcode", "None", 0},
{"EOR ", " Exclusive OR", "Absolute_X", 2},
{"LSR ", " Logical Shift Right", "Absolute_X", 2},
{"SCF", " Stop, Catch Fire: Illegal Opcode", "None", 0},
{"RTS ", " Return from Subroutine", "Implied", 0},
{"ADC ", " Add with Carry", "Indirect_X", 1},
{"SCF", " Stop, Catch Fire: Illegal Opcode", "None", 0},
{"SCF", " Stop, Catch Fire: Illegal Opcode", "None", 0},
{"SCF", " Stop, Catch Fire: Illegal Opcode", "None", 0},
{"ADC ", " Add with Carry", "ZeroPage", 1},
{"ROR ", " Rotate Right", "ZeroPage", 1},
{"SCF", " Stop, Catch Fire: Illegal Opcode", "None", 0},
{"PLA ", " Pull Accumulator", "Implied", 0},
{"ADC ", " Add with Carry", "Immediate", 1},
{"ROR ", " Rotate Right", "Accumulator", 0},
{"SCF", " Stop, Catch Fire: Illegal Opcode", "None", 0},
{"JMP ", " Jump", "Indirect", 2},
{"ADC ", " Add with Carry", "Absolute", 2},
{"ROR ", " Rotate Right", "Absolute", 2},
{"SCF", " Stop, Catch Fire: Illegal Opcode", "None", 0},
{"BVS ", " Branch if Overflow Set", "Relative", 1},
{"ADC ", " Add with Carry", "Indirect_Y", 1},
{"SCF", " Stop, Catch Fire: Illegal Opcode", "None", 0},
{"SCF", " Stop, Catch Fire: Illegal Opcode", "None", 0},
{"SCF", " Stop, Catch Fire: Illegal Opcode", "None", 0},
{"ADC ", " Add with Carry", "ZeroPage_X", 1},
{"ROR ", " Rotate Right", "ZeroPage_X", 1},
{"SCF", " Stop, Catch Fire: Illegal Opcode", "None", 0},
{"SEI ", " Set Interrupt Disable", "Implied", 0},
{"ADC ", " Add with Carry", "Absolute_Y", 2},
{"SCF", " Stop, Catch Fire: Illegal Opcode", "None", 0},
{"SCF", " Stop, Catch Fire: Illegal Opcode", "None", 0},
{"SCF", " Stop, Catch Fire: Illegal Opcode", "None", 0},
{"ADC ", " Add with Carry", "Absolute_X", 2},
{"ROR ", " Rotate Right", "Absolute_X", 2},
{"SCF", " Stop, Catch Fire: Illegal Opcode", "None", 0},
{"SCF", " Stop, Catch Fire: Illegal Opcode", "None", 0},
{"STA ", " Store Accumulator", "Indirect_X", 1},
{"SCF", " Stop, Catch Fire: Illegal Opcode", "None", 0},
{"SCF", " Stop, Catch Fire: Illegal Opcode", "None", 0},
{"STY ", " Store Y Register", "ZeroPage", 1},
{"STA ", " Store Accumulator", "ZeroPage", 1},
{"STX ", " Store X Register", "ZeroPage", 1},
{"SCF", " Stop, Catch Fire: Illegal Opcode", "None", 0},
{"DEY ", " Decrement Y Register", "Implied", 0},
{"SCF", " Stop, Catch Fire: Illegal Opcode", "None", 0},
{"TXA ", " Transfer X to Accumulator", "Implied", 0},
{"SCF", " Stop, Catch Fire: Illegal Opcode", "None", 0},
{"STY ", " Store Y Register", "Absolute", 2},
{"STA ", " Store Accumulator", "Absolute", 2},
{"STX ", " Store X Register", "Absolute", 2},
{"SCF", " Stop, Catch Fire: Illegal Opcode", "None", 0},
{"BCC ", " Branch if Carry Clear", "Relative", 1},
{"STA ", " Store Accumulator", "Indirect_Y", 1},
{"SCF", " Stop, Catch Fire: Illegal Opcode", "None", 0},
{"SCF", " Stop, Catch Fire: Illegal Opcode", "None", 0},
{"STY ", " Store Y Register", "ZeroPage_X", 1},
{"STA ", " Store Accumulator", "ZeroPage_X", 1},
{"STX ", " Store X Register", "ZeroPage_Y", 1},
{"SCF", " Stop, Catch Fire: Illegal Opcode", "None", 0},
{"TYA ", " Transfer Y to Accumulator", "Implied", 0},
{"STA ", " Store Accumulator", "Absolute_Y", 2},
{"TXS ", " Transfer X to Stack Pointer", "Implied", 0},
{"SCF", " Stop, Catch Fire: Illegal Opcode", "None", 0},
{"SCF", " Stop, Catch Fire: Illegal Opcode", "None", 0},
{"STA ", " Store Accumulator", "Absolute_X", 2},
{"SCF", " Stop, Catch Fire: Illegal Opcode", "None", 0},
{"SCF", " Stop, Catch Fire: Illegal Opcode", "None", 0},
{"LDY ", " Load Y Register", "Immediate", 1},
{"LDA ", " Load Accumulator", "Indirect_X", 1},
{"LDX ", " Load X Register", "Immediate", 1},
{"SCF", " Stop, Catch Fire: Illegal Opcode", "None", 0},
{"LDY ", " Load Y Register", "ZeroPage", 1},
{"LDA ", " Load Accumulator", "ZeroPage", 1},
{"LDX ", " Load X Register", "ZeroPage", 1},
{"SCF", " Stop, Catch Fire: Illegal Opcode", "None", 0},
{"TAY ", " Transfer Accumulator to Y", "Implied", 0},
{"LDA ", " Load Accumulator", "Immediate", 1},
{"TAX ", " Transfer Accumulator to X", "Implied", 0},
{"SCF", " Stop, Catch Fire: Illegal Opcode", "None", 0},
{"LDY ", " Load Y Register", "Absolute", 2},
{"LDA ", " Load Accumulator", "Absolute", 2},
{"LDX ", " Load X Register", "Absolute", 2},
{"SCF", " Stop, Catch Fire: Illegal Opcode", "None", 0},
{"BCS ", " Branch if Carry Set", "Relative", 1},
{"LDA ", " Load Accumulator", "Indirect_Y", 1},
{"SCF", " Stop, Catch Fire: Illegal Opcode", "None", 0},
{"SCF", " Stop, Catch Fire: Illegal Opcode", "None", 0},
{"LDY ", " Load Y Register", "ZeroPage_X", 1},
{"LDA ", " Load Accumulator", "ZeroPage_X", 1},
{"LDX ", " Load X Register", "ZeroPage_Y", 1},
{"SCF", " Stop, Catch Fire: Illegal Opcode", "None", 0},
{"CLV ", " Clear Overflow Flag", "Implied", 0},
{"LDA ", " Load Accumulator", "Absolute_Y", 2},
{"TSX ", " Transfer Stack Pointer to X", "Implied", 0},
{"SCF", " Stop, Catch Fire: Illegal Opcode", "None", 0},
{"LDY ", " Load Y Register", "Absolute_X", 2},
{"LDA ", " Load Accumulator", "Absolute_X", 2},
{"LDX ", " Load X Register", "Absolute_Y", 2},
{"SCF", " Stop, Catch Fire: Illegal Opcode", "None", 0},
{"CPY ", " Compare Y Register", "Immediate", 1},
{"CMP ", " Compare", "Indirect_X", 1},
{"SCF", " Stop, Catch Fire: Illegal Opcode", "None", 0},
{"SCF", " Stop, Catch Fire: Illegal Opcode", "None", 0},
{"CPY ", " Compare Y Register", "ZeroPage", 1},
{"CMP ", " Compare", "ZeroPage", 1},
{"DEC ", " Decrement Memory", "ZeroPage", 1},
{"SCF", " Stop, Catch Fire: Illegal Opcode", "None", 0},
{"INY ", " Increment Y Register", "Implied", 0},
{"CMP ", " Compare", "Immediate", 1},
{"DEX ", " Decrement X Register", "Implied", 0},
{"SCF", " Stop, Catch Fire: Illegal Opcode", "None", 0},
{"CPY ", " Compare Y Register", "Absolute", 2},
{"CMP ", " Compare", "Absolute", 2},
{"DEC ", " Decrement Memory", "Absolute", 2},
{"SCF", " Stop, Catch Fire: Illegal Opcode", "None", 0},
{"BNE ", " Branch if Not Equal", "Relative", 1},
{"CMP ", " Compare", "Indirect_Y", 1},
{"SCF", " Stop, Catch Fire: Illegal Opcode", "None", 0},
{"SCF", " Stop, Catch Fire: Illegal Opcode", "None", 0},
{"SCF", " Stop, Catch Fire: Illegal Opcode", "None", 0},
{"CMP ", " Compare", "ZeroPage_X", 1},
{"DEC ", " Decrement Memory", "ZeroPage_X", 1},
{"SCF", " Stop, Catch Fire: Illegal Opcode", "None", 0},
{"CLD ", " Clear Decimal Mode", "Implied", 0},
{"CMP ", " Compare", "Absolute_Y", 2},
{"SCF", " Stop, Catch Fire: Illegal Opcode", "None", 0},
{"SCF", " Stop, Catch Fire: Illegal Opcode", "None", 0},
{"SCF", " Stop, Catch Fire: Illegal Opcode", "None", 0},
{"CMP ", " Compare", "Absolute_X", 2},
{"DEC ", " Decrement Memory", "Absolute_X", 2},
{"SCF", " Stop, Catch Fire: Illegal Opcode", "None", 0},
{"CPX ", " Compare X Register", "Immediate", 1},
{"SBC ", " Subtract with Carry", "Indirect_X", 1},
{"SCF", " Stop, Catch Fire: Illegal Opcode", "None", 0},
{"SCF", " Stop, Catch Fire: Illegal Opcode", "None", 0},
{"CPX ", " Compare X Register", "ZeroPage", 1},
{"SBC ", " Subtract with Carry", "ZeroPage", 1},
{"INC ", " Increment Memory", "ZeroPage", 1},
{"SCF", " Stop, Catch Fire: Illegal Opcode", "None", 0},
{"INX ", " Increment X Register", "Implied", 0},
{"SBC ", " Subtract with Carry", "Immediate", 1},
{"NOP ", " No Operation", "Implied", 0},
{"SCF", " Stop, Catch Fire: Illegal Opcode", "None", 0},
{"CPX ", " Compare X Register", "Absolute", 2},
{"SBC ", " Subtract with Carry", "Absolute", 2},
{"INC ", " Increment Memory", "Absolute", 2},
{"SCF", " Stop, Catch Fire: Illegal Opcode", "None", 0},
{"BEQ ", " Branch if Equal", "Relative", 1},
{"SBC ", " Subtract with Carry", "Indirect_Y", 1},
{"SCF", " Stop, Catch Fire: Illegal Opcode", "None", 0},
{"SCF", " Stop, Catch Fire: Illegal Opcode", "None", 0},
{"SCF", " Stop, Catch Fire: Illegal Opcode", "None", 0},
{"SBC ", " Subtract with Carry", "ZeroPage_X", 1},
{"INC ", " Increment Memory", "ZeroPage_X", 1},
{"SCF", " Stop, Catch Fire: Illegal Opcode", "None", 0},
{"SED ", " Set Decimal Flag", "Implied", 0},
{"SBC ", " Subtract with Carry", "Absolute_Y", 2},
{"SCF", " Stop, Catch Fire: Illegal Opcode", "None", 0},
{"SCF", " Stop, Catch Fire: Illegal Opcode", "None", 0},
{"SCF", " Stop, Catch Fire: Illegal Opcode", "None", 0},
{"SBC ", " Subtract with Carry", "Absolute_X", 2},
{"INC ", " Increment Memory", "Absolute_X", 2},
    {"SCF", " Stop, Catch Fire: Illegal Opcode", "None"}
};